# Generated by Django 5.2.17 on 2026-08-31 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_gamerprofile_location_public_venue_category_and_more"),
        ("events", "0002_event_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("description", models.TextField(blank=True, max_length=3000)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("Organization", "Organization"),
                            ("Brand", "Brand"),
                            ("Venue", "Venue"),
                            ("Team", "Team"),
                            ("Community", "Community"),
                        ],
                        default="Organization",
                        max_length=30,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("social_link", models.URLField(blank=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organizations/logos/"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Verified", "Verified"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=15,
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_organizations",
                        to="accounts.gamerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="EventPromotionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("Featured Event", "Featured Event"),
                            ("Homepage Placement", "Homepage Placement"),
                            ("Tournament Sponsorship", "Tournament Sponsorship"),
                            ("Venue Promotion", "Venue Promotion"),
                        ],
                        default="Featured Event",
                        max_length=30,
                    ),
                ),
                ("campaign_description", models.TextField(blank=True, max_length=2000)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Cancelled", "Cancelled"),
                            ("Expired", "Expired"),
                        ],
                        default="Pending",
                        max_length=15,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_requests",
                        to="events.event",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_promotions",
                        to="accounts.gamerprofile",
                    ),
                ),
                (
                    "requesting_organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_requests",
                        to="events.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="event",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.organization",
            ),
        ),
    ]
