# Generated by Django 5.2.17 on 2026-08-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_featured_organization_eventpromotionrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="event",
            name="country",
            field=models.CharField(blank=True, default="Zimbabwe", max_length=100),
        ),
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="location_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="province",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="organization",
            name="country",
            field=models.CharField(blank=True, default="Zimbabwe", max_length=100),
        ),
        migrations.AddField(
            model_name="organization",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="location_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="province",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
