# Generated by Django 5.2.17 on 2026-08-31 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_city_event_country_event_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Published", "Published"),
                    ("Upcoming", "Upcoming"),
                    ("Live", "Live"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Upcoming",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="eventpromotionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Submitted", "Submitted"),
                    ("Under Review", "Under Review"),
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Active", "Active"),
                    ("Completed", "Completed"),
                    ("Rejected", "Rejected"),
                    ("Cancelled", "Cancelled"),
                    ("Expired", "Expired"),
                ],
                default="Pending",
                max_length=15,
            ),
        ),
    ]
