# Generated by Django 5.2.17 on 2026-09-01 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_externalfeeditem"),
        ("events", "0005_alter_event_status_and_more"),
        ("games", "0006_gamereview_gamewishlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("Gaming Hub", "Gaming Hub"),
                            ("Esports Arena", "Esports Arena"),
                            ("LAN Centre", "LAN Centre"),
                            ("Gaming Café", "Gaming Café"),
                            ("PC Shop", "PC Shop"),
                            ("Developer Studio", "Developer Studio"),
                            ("Tech Business", "Tech Business"),
                            ("Gaming Club", "Gaming Club"),
                        ],
                        default="Gaming Hub",
                        max_length=40,
                    ),
                ),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=120)),
                (
                    "country",
                    models.CharField(blank=True, default="Zimbabwe", max_length=100),
                ),
                ("description", models.TextField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("website", models.URLField(blank=True)),
                ("social_links", models.JSONField(blank=True, default=list)),
                ("opening_hours", models.CharField(blank=True, max_length=250)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("photos", models.JSONField(blank=True, default=list)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("UNVERIFIED", "Unverified"),
                            ("VERIFIED", "Verified"),
                            ("SUSPENDED", "Suspended"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="UNVERIFIED",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("RADAR", "Radar"),
                            ("FEATURED", "Featured"),
                        ],
                        default="FREE",
                        max_length=20,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("public_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "games",
                    models.ManyToManyField(
                        blank=True, related_name="radar_locations", to="games.game"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="events.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="OrganizationLocationRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="events.organizationlocation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radar_location_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationLocationReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("review_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radar_location_reviews",
                        to="accounts.gamerprofile",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="events.organizationlocation",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="organizationlocation",
            index=models.Index(
                fields=["verification_status", "public_visible"],
                name="events_orga_verific_9d0535_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationlocation",
            index=models.Index(
                fields=["city", "country"], name="events_orga_city_43084d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationlocationrating",
            constraint=models.UniqueConstraint(
                fields=("location", "user"), name="unique_radar_location_rating"
            ),
        ),
    ]
