services:
  - type: web
    name: ggz-zimbabwe
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput
      gunicorn hello_world.wsgi:application --bind 0.0.0.0:$PORT
