# Generated by Django 5.2.17 on 2026-08-25 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0009_remove_report_report_has_one_target_and_more"),
        ("games", "0003_game_player_count_game_popularity_game_release_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(max_length=3000)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Gaming PCs", "Gaming PCs"),
                            ("Gaming Laptops", "Gaming Laptops"),
                            ("PlayStation", "PlayStation"),
                            ("Xbox", "Xbox"),
                            ("Nintendo", "Nintendo"),
                            ("PC Games", "PC Games"),
                            ("Consoles", "Consoles"),
                            ("Controllers", "Controllers"),
                            ("GPUs", "GPUs"),
                            ("CPUs", "CPUs"),
                            ("Monitors", "Monitors"),
                            ("Keyboards", "Keyboards"),
                            ("Mice", "Mice"),
                            ("Headsets", "Headsets"),
                            ("Gaming Chairs", "Gaming Chairs"),
                            ("Accessories", "Accessories"),
                            ("Other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Like New", "Like New"),
                            ("Good", "Good"),
                            ("Fair", "Fair"),
                            ("Used", "Used"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("platform", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Reserved", "Reserved"),
                            ("Sold", "Sold"),
                        ],
                        default="Available",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings",
                        to="games.game",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="accounts.gamerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="listings/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="marketplace.listing",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SavedListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saves",
                        to="marketplace.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_listings",
                        to="accounts.gamerprofile",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["status", "category"], name="marketplace_status_a6670d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["location"], name="marketplace_locatio_a1aedc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="savedlisting",
            constraint=models.UniqueConstraint(
                fields=("user", "listing"), name="unique_saved_listing"
            ),
        ),
    ]
