# Generated by Django 5.2.17 on 2026-08-25 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0009_remove_report_report_has_one_target_and_more"),
        ("games", "0003_game_player_count_game_popularity_game_release_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("description", models.TextField(max_length=3000)),
                (
                    "banner",
                    models.ImageField(blank=True, null=True, upload_to="tournaments/"),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("1v1", "1v1"),
                            ("2v2", "2v2"),
                            ("3v3", "3v3"),
                            ("4v4", "4v4"),
                            ("5v5", "5v5"),
                            ("Free For All", "Free For All"),
                        ],
                        max_length=20,
                    ),
                ),
                ("max_participants", models.PositiveIntegerField(default=32)),
                ("start_date", models.DateTimeField()),
                ("registration_deadline", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "mode",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        default="online",
                        max_length=10,
                    ),
                ),
                ("entry_type", models.CharField(default="Free", max_length=20)),
                ("prize_description", models.CharField(blank=True, max_length=300)),
                ("rules", models.TextField(blank=True, max_length=3000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Registration Open", "Registration Open"),
                            ("Registration Closed", "Registration Closed"),
                            ("Live", "Live"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Draft",
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournaments",
                        to="games.game",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_tournaments",
                        to="accounts.gamerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("start_date",),
            },
        ),
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Declined", "Declined"),
                            ("Cancelled", "Cancelled"),
                            ("Scheduled", "Scheduled"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=15,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenges_made",
                        to="accounts.gamerprofile",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenges",
                        to="games.game",
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenges_received",
                        to="accounts.gamerprofile",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="challenges",
                        to="tournaments.tournament",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round", models.PositiveIntegerField(default=1)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.CharField(blank=True, max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Scheduled", "Scheduled"),
                            ("Live", "Live"),
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Scheduled",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="games.game",
                    ),
                ),
                (
                    "player_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_one",
                        to="accounts.gamerprofile",
                    ),
                ),
                (
                    "player_two",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_two",
                        to="accounts.gamerprofile",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="tournaments.tournament",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_won",
                        to="accounts.gamerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TournamentRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Registered", "Registered"),
                            ("Waitlisted", "Waitlisted"),
                            ("Withdrawn", "Withdrawn"),
                            ("Disqualified", "Disqualified"),
                        ],
                        default="Registered",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tournament_registrations",
                        to="accounts.gamerprofile",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="tournaments.tournament",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["status", "start_date"], name="tournaments_status_59e85f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tournament",
            index=models.Index(
                fields=["location"], name="tournaments_locatio_3cc792_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="challenge",
            constraint=models.CheckConstraint(
                condition=models.Q(("challenger", models.F("opponent")), _negated=True),
                name="no_self_challenge",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentmatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("player_one", models.F("player_two")), _negated=True
                ),
                name="match_players_are_different",
            ),
        ),
        migrations.AddConstraint(
            model_name="tournamentregistration",
            constraint=models.UniqueConstraint(
                fields=("tournament", "player"), name="unique_tournament_registration"
            ),
        ),
    ]
