# Generated by Django 5.2.17 on 2026-08-26 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_conversation_conversationparticipant_and_more"),
        ("tournaments", "0002_tournamentmatch_next_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamentmatch",
            name="player_one",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_one",
                to="accounts.gamerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="tournamentmatch",
            name="player_two",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_two",
                to="accounts.gamerprofile",
            ),
        ),
    ]
