# Generated by Django 5.2.17 on 2026-08-30 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_gamerprofile_location_public_venue_category_and_more"),
        ("tournaments", "0003_alter_tournamentmatch_player_one_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournament",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="tournament",
            name="country",
            field=models.CharField(blank=True, default="Zimbabwe", max_length=100),
        ),
        migrations.AddField(
            model_name="tournament",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="province",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="tournament",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tournaments",
                to="accounts.venue",
            ),
        ),
    ]
