# Generated by Django 5.2.17 on 2026-09-13 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('tournaments', '0005_tournamentinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_registrations', to='teams.team'),
        ),
    ]
