# Generated by Django 5.2.17 on 2026-08-23 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GamerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gamer_tag", models.CharField(max_length=50, unique=True)),
                ("bio", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PC", "PC"),
                            ("PlayStation", "PlayStation"),
                            ("Xbox", "Xbox"),
                            ("Nintendo", "Nintendo"),
                            ("Mobile", "Mobile"),
                        ],
                        max_length=20,
                    ),
                ),
                ("respect_points", models.PositiveIntegerField(default=0)),
                ("tournament_wins", models.PositiveIntegerField(default=0)),
                ("youtube", models.URLField(blank=True)),
                ("social_link", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gamer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
