# Generated by Django 5.2.17 on 2026-08-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamerprofile",
            name="games",
            field=models.ManyToManyField(
                blank=True, related_name="players", to="games.game"
            ),
        ),
    ]
