# Generated by Django 5.2.17 on 2026-08-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_gamerprofile_games"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamerprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
