# Generated by Django 5.2.17 on 2026-08-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_gamerprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamerprofile",
            name="availability",
            field=models.CharField(
                choices=[
                    ("Available", "Available to play"),
                    ("Sometimes", "Sometimes available"),
                    ("Busy", "Usually busy"),
                ],
                default="Sometimes",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gamerprofile",
            name="discord_username",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="gamerprofile",
            name="playstation_username",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="gamerprofile",
            name="rank",
            field=models.CharField(
                choices=[
                    ("Unranked", "Unranked"),
                    ("Bronze", "Bronze"),
                    ("Silver", "Silver"),
                    ("Gold", "Gold"),
                    ("Platinum", "Platinum"),
                    ("Diamond", "Diamond"),
                    ("Master", "Master"),
                ],
                default="Unranked",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gamerprofile",
            name="riot_username",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="gamerprofile",
            name="steam_username",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="gamerprofile",
            name="xbox_username",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
