# Generated by Django 5.2.17 on 2026-08-25 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_post_comment_postlike"),
    ]

    operations = [
        migrations.CreateModel(
            name="RespectTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "giver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respect_given",
                        to="accounts.gamerprofile",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respect_received",
                        to="accounts.gamerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("giver", "recipient"), name="unique_respect_transaction"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("giver", models.F("recipient")), _negated=True
                        ),
                        name="no_self_respect",
                    ),
                ],
            },
        ),
    ]
