# Generated by Django 5.2.17 on 2026-08-25 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_respecttransaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Harassment"),
                            ("scam", "Scam"),
                            ("inappropriate", "Inappropriate content"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("details", models.TextField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="accounts.post",
                    ),
                ),
                (
                    "reported_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to="accounts.gamerprofile",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to="accounts.gamerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("reported_profile__isnull", False),
                                ("post__isnull", True),
                            ),
                            models.Q(
                                ("reported_profile__isnull", True),
                                ("post__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="report_has_one_target",
                    ),
                    models.UniqueConstraint(
                        fields=("reporter", "reported_profile"),
                        name="unique_profile_report",
                    ),
                    models.UniqueConstraint(
                        fields=("reporter", "post"), name="unique_post_report"
                    ),
                ],
            },
        ),
    ]
