# Generated by Django 5.2.17 on 2026-08-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_report"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="report",
            name="report_has_one_target",
        ),
        migrations.AddField(
            model_name="report",
            name="reported_listing_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("reported_profile__isnull", False),
                        ("post__isnull", True),
                        ("reported_listing_id__isnull", True),
                    ),
                    models.Q(
                        ("reported_profile__isnull", True),
                        ("post__isnull", False),
                        ("reported_listing_id__isnull", True),
                    ),
                    models.Q(
                        ("reported_profile__isnull", True),
                        ("post__isnull", True),
                        ("reported_listing_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="report_has_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("reporter", "reported_listing_id"), name="unique_listing_report"
            ),
        ),
    ]
