# Generated by Django 5.2.17 on 2026-08-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_conversation_conversationparticipant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationparticipant",
            name="cleared_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
