# Generated by Django 5.2.17 on 2026-08-26 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_conversationparticipant_cleared_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Declined", "Declined"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_requests_received",
                        to="accounts.gamerprofile",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_requests_sent",
                        to="accounts.gamerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sender", "recipient"), name="unique_message_request"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sender", models.F("recipient")), _negated=True
                        ),
                        name="message_request_no_self",
                    ),
                ],
            },
        ),
    ]
