# Generated by Django 5.2.17 on 2026-08-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_venue_gamerprofile_city_gamerprofile_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamerprofile",
            name="location_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="category",
            field=models.CharField(
                choices=[
                    ("Gaming Lounge", "Gaming Lounge"),
                    ("Esports Venue", "Esports Venue"),
                    ("LAN Center", "LAN Center"),
                    ("PC Gaming Shop", "PC Gaming Shop"),
                    ("Console Shop", "Console Shop"),
                    ("Gaming Cafe", "Gaming Cafe"),
                    ("Computer/Tech Shop", "Computer/Tech Shop"),
                    ("Tournament Venue", "Tournament Venue"),
                ],
                default="Gaming Lounge",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="venue",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="opening_hours",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="venue",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="venue",
            name="social_link",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
