# Generated by Django 5.2.17 on 2026-09-01 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_postsave"),
        ("games", "0006_gamereview_gamewishlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalFeedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=120)),
                ("source_url", models.URLField(blank=True)),
                ("title", models.CharField(max_length=300)),
                ("excerpt", models.TextField(blank=True)),
                ("url", models.URLField()),
                ("image_url", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("NEWS", "News"),
                            ("VIDEO", "Video"),
                            ("TRAILER", "Trailer"),
                            ("ANNOUNCEMENT", "Announcement"),
                            ("UPDATE", "Update"),
                            ("ESPORTS", "Esports"),
                        ],
                        default="NEWS",
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "game",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_feed_items",
                        to="games.game",
                    ),
                ),
            ],
            options={
                "ordering": ("-published_at", "-fetched_at"),
            },
        ),
    ]
