# Generated by Django 5.2.17 on 2026-09-07 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_socialidentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamerprofile",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="covers/"),
        ),
        migrations.CreateModel(
            name="GamerPresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manual_status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("away", "Away"),
                            ("invisible", "Invisible"),
                        ],
                        default="online",
                        max_length=12,
                    ),
                ),
                ("last_activity", models.DateTimeField(blank=True, null=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("show_online_status", models.BooleanField(default=True)),
                ("show_last_seen", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presence",
                        to="accounts.gamerprofile",
                    ),
                ),
            ],
        ),
    ]
