# Generated by Django 5.2.17 on 2026-09-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialidentity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='socialidentity',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('apple', 'Apple'), ('discord', 'Discord')], max_length=20),
        ),
    ]
