"""
Django settings for hello_world project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/topics/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlsplit

from decouple import config


def comma_separated(value):
    return [item.strip() for item in value.split(",") if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# Deployed platforms set one of these values. Local development remains usable
# without an .env file, while deployed hosts and origins must be explicit.
DEPLOYED = bool(os.environ.get("VERCEL") or os.environ.get("RENDER_EXTERNAL_HOSTNAME") or os.environ.get("DATABASE_URL"))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "DJANGO_SECRET_KEY",
    default="dev-secret-key-change-me-for-local-ggz-development-2026-!",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=not DEPLOYED, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="" if DEPLOYED else "localhost,127.0.0.1,[::1]",
    cast=comma_separated,
)

CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="" if DEPLOYED else "http://localhost:8000,http://127.0.0.1:8000,https://localhost:8000,https://127.0.0.1:8000",
    cast=comma_separated,
)

ALLOWED_HOSTS = list(dict.fromkeys(ALLOWED_HOSTS))
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(CSRF_TRUSTED_ORIGINS))

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_browser_reload",

    "accounts",
    "games",
    "tournaments",
    "marketplace",
    "events",
    "teams",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

X_FRAME_OPTIONS = config("X_FRAME_OPTIONS", default="DENY")
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if config("USE_X_FORWARDED_PROTO", default=DEPLOYED, cast=bool)
    else None
)

ROOT_URLCONF = "hello_world.urls"

LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "/accounts/login/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

# Keep local development usable while hardening session and CSRF cookies.
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=DEPLOYED and not DEBUG, cast=bool)
SECURE_HSTS_SECONDS = config(
    "SECURE_HSTS_SECONDS",
    default=31536000 if not DEBUG else 0,
    cast=int,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG
SECURE_HSTS_PRELOAD = not DEBUG
SECURE_BROWSER_XSS_FILTER = not DEBUG

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "hello_world" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "accounts.context_processors.notification_count",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hello_world.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

database_url = os.environ.get("DATABASE_URL", "").strip()
if database_url:
    parsed_database_url = urlsplit(database_url)
    if parsed_database_url.scheme not in {"postgres", "postgresql", "sqlite"}:
        raise ValueError("DATABASE_URL must use postgres, postgresql, or sqlite")
    if parsed_database_url.scheme == "sqlite":
        database_name = unquote(parsed_database_url.path)
        if database_name.startswith("/") and not database_name.startswith("//"):
            database_name = database_name[1:]
        DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": database_name}}
    else:
        database_query = parse_qs(parsed_database_url.query)
        sslmode = database_query.get("sslmode", [os.environ.get("PGSSLMODE", "require")])[0]
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": unquote(parsed_database_url.path.lstrip("/")),
                "USER": unquote(parsed_database_url.username or ""),
                "PASSWORD": unquote(parsed_database_url.password or ""),
                "HOST": parsed_database_url.hostname or "",
                "PORT": str(parsed_database_url.port or ""),
                "OPTIONS": {"sslmode": sslmode},
                # Serverless workers should not hold connections indefinitely.
                "CONN_MAX_AGE": config("DB_CONN_MAX_AGE", default=0, cast=int),
                "CONN_HEALTH_CHECKS": True,
            }
        }
else:
    DATABASES = {
        "default": {
            "ENGINE": config("DB_ENGINE", default="django.db.backends.sqlite3"),
            "NAME": config("DB_NAME", default=str(BASE_DIR / "db.sqlite3")),
            "USER": config("DB_USER", default=""),
            "PASSWORD": config("DB_PASSWORD", default=""),
            "HOST": config("DB_HOST", default=""),
            "PORT": config("DB_PORT", default=""),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATICFILES_DIRS = [
    BASE_DIR / "hello_world" / "static",
]

STATIC_URL = config("STATIC_URL", default="static/")
STATIC_ROOT = Path(config("STATIC_ROOT", default=str(BASE_DIR / "staticfiles")))

MEDIA_URL = config("MEDIA_URL", default="media/")
MEDIA_ROOT = Path(config("MEDIA_ROOT", default=str(BASE_DIR / "hello_world" / "media")))

S3_STORAGE_VARIABLES = (
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_STORAGE_BUCKET_NAME",
    "AWS_S3_ENDPOINT_URL",
    "AWS_S3_REGION_NAME",
)
USE_S3_MEDIA_STORAGE = all(os.environ.get(name) for name in S3_STORAGE_VARIABLES)

if USE_S3_MEDIA_STORAGE:
    s3_endpoint = urlsplit(os.environ["AWS_S3_ENDPOINT_URL"])
    s3_bucket = os.environ["AWS_STORAGE_BUCKET_NAME"]
    s3_public_domain = os.environ.get("AWS_S3_CUSTOM_DOMAIN", "")
    if not s3_public_domain and s3_endpoint.hostname and s3_endpoint.hostname.endswith(".supabase.co"):
        s3_public_domain = s3_endpoint.hostname
    if not s3_public_domain:
        raise ValueError("AWS_S3_CUSTOM_DOMAIN is required for non-Supabase S3 media storage")

    s3_public_path = f"storage/v1/object/public/{s3_bucket}"
    MEDIA_URL = f"https://{s3_public_domain}/{s3_public_path}/"
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "access_key": os.environ["AWS_ACCESS_KEY_ID"],
                "secret_key": os.environ["AWS_SECRET_ACCESS_KEY"],
                "bucket_name": s3_bucket,
                "endpoint_url": os.environ["AWS_S3_ENDPOINT_URL"],
                "region_name": os.environ["AWS_S3_REGION_NAME"],
                "custom_domain": f"{s3_public_domain}/{s3_public_path}",
                "querystring_auth": False,
                "file_overwrite": False,
            },
        },
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

GOOGLE_MAPS_PROVIDER = config("GOOGLE_MAPS_PROVIDER", default=config("GGZ_MAP_PROVIDER", default="google"))
GOOGLE_MAPS_API_KEY = config("GOOGLE_MAPS_API_KEY", default=config("GGZ_MAP_API_KEY", default=""))
GOOGLE_MAPS_MAP_ID = config("GOOGLE_MAPS_MAP_ID", default=config("GGZ_MAP_ID", default=""))
GOOGLE_MAPS_MIN_HOTSPOT_GAMERS = config("GOOGLE_MAPS_MIN_HOTSPOT_GAMERS", default=config("GGZ_MAP_MIN_HOTSPOT_GAMERS", default=3, cast=int), cast=int)
GOOGLE_MAPS_DEFAULT_LATITUDE = config("GOOGLE_MAPS_DEFAULT_LATITUDE", default=config("GGZ_MAP_DEFAULT_LATITUDE", default=-17.8252, cast=float), cast=float)
GOOGLE_MAPS_DEFAULT_LONGITUDE = config("GOOGLE_MAPS_DEFAULT_LONGITUDE", default=config("GGZ_MAP_DEFAULT_LONGITUDE", default=31.0335, cast=float), cast=float)

# Backward-compatible aliases for older deployments and local environments.
GGZ_MAP_PROVIDER = GOOGLE_MAPS_PROVIDER
GGZ_MAP_API_KEY = GOOGLE_MAPS_API_KEY
GGZ_MAP_ID = GOOGLE_MAPS_MAP_ID
GGZ_MAP_MIN_HOTSPOT_GAMERS = GOOGLE_MAPS_MIN_HOTSPOT_GAMERS
GGZ_MAP_DEFAULT_LATITUDE = GOOGLE_MAPS_DEFAULT_LATITUDE
GGZ_MAP_DEFAULT_LONGITUDE = GOOGLE_MAPS_DEFAULT_LONGITUDE

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
