# Generated by Django 5.2.17 on 2026-08-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="cover_art_url",
            field=models.URLField(blank=True),
        ),
    ]
