# Generated by Django 5.2.17 on 2026-08-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_game_cover_art_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="player_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="popularity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="game",
            name="release_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
