# Generated by Django 5.2.17 on 2026-09-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_game_player_count_game_popularity_game_release_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="free_to_play",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="local_developer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="sponsored",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="store_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="game",
            name="trailer_url",
            field=models.URLField(blank=True),
        ),
    ]
