# Generated by Django 5.2.17 on 2026-09-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_game_featured_game_free_to_play_game_local_developer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="epic_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="game",
            name="steam_url",
            field=models.URLField(blank=True),
        ),
    ]
