# Generated by Django 5.2.17 on 2026-09-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gamereview_gamewishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='igdb_genres',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_last_synced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_platforms',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_rating_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_slug',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='game',
            name='igdb_url',
            field=models.URLField(blank=True),
        ),
    ]
