# Generated by Django 5.2.17 on 2026-09-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_igdb_genres_game_igdb_id_game_igdb_last_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='twitch_category_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='twitch_category_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
